---
name: es-kafka
env: svil
namespace: myproject
ibmLicenseUse: EventAutomationNonProduction
kafka_replicas: 1
kafka_storage_size: 1Gi
zookeeper_replicas: 1
zookeeper_storage_size: 1Gi
storageclassname: crc-csi-hostpath-provisioner
#image: 
#  repository: docker.io/fdaluisio/fd-sql-runner
#  version: v1
#  imagepullpolicy: Always