apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  annotations:
    eventstreams.ibm.com/apicurio-registry-version: '>=2.4'
  name: {{ .Values.env }}-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
spec:
  adminApi:
    resources:
        limits:
          cpu: 2
          memory: 1Gi
        requests:
          cpu: 0.5
          memory: 1Gi
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: pot-ibm-event-stream
                      operator: In
                      values:
                        - deloitte
  adminUI:
    resources:
        limits:
          cpu: 1.1
          memory: 600Mi
        requests:
          cpu: 0.35
          memory: 600Mi
    authentication:
      - type: scram-sha-512
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: pot-ibm-event-stream
                      operator: In
                      values:
                        - deloitte
  apicurioRegistry:
    resources:
        limits:
          cpu: 0.9
          memory: 1250Mi
        requests:
          cpu: 0.9
          memory: 1250Mi
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: pot-ibm-event-stream
                      operator: In
                      values:
                        - deloitte
  collector: {}
  license:
    accept: true
    license: L-HRZF-DWHH7A
    use: {{ .Values.ibmLicenseUse }}
  restProducer:
    resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 0.25
          memory: 1Gi
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: pot-ibm-event-stream
                      operator: In
                      values:
                        - deloitte
  strimziOverrides:
    entityOperator:
      resources:
          limits:
            cpu: 2.1
            memory: 1Gi
          requests:
            cpu: 0.1
            memory: 1Gi
      topicOperator: {}
    kafka:
      authorization:
        type: simple
      config:
        default.replication.factor: 3
        inter.broker.protocol.version: '3.6'
        log.cleaner.threads: 6
        min.insync.replicas: 1
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
      listeners:
        - authentication:
            type: scram-sha-512
          name: external
          port: 9094
          tls: true
          type: route
        - authentication:
            type: tls
          name: tls
          port: 9093
          tls: true
          type: internal
        - authentication:
            type: scram-sha-512
          name: plain
          port: 9092
          type: internal
          tls: false
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: development-metrics-config
      replicas: {{ .Values.kafka_replicas }}
      resources:
        limits:
          cpu: 1
          memory: 4096Mi
        requests:
          cpu: 0.5
          memory: 4096Mi
      storage:
        class: {{ .Values.storageclassname }}
        size: {{ .Values.kafka_storage_size }}
        type: persistent-claim
      template:
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: pot-ibm-event-stream
                        operator: In
                        values:
                          - deloitte
    zookeeper:
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: development-metrics-config
      replicas: {{ .Values.zookeeper_replicas }}
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 0.5
          memory: 1Gi
      storage:
        class: {{ .Values.storageclassname }}
        size: {{ .Values.zookeeper_storage_size }}
        type: persistent-claim
  version: latest
