apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: fd-kafkauser
  labels:
    eventstreams.ibm.com/cluster: svil-es-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - Write
          - Read
          - Create
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - Read
      - resource:
          type: topic
          name: __schema_
          patternType: prefix
        operations:
          - Read
          - Alter

